// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: md5er.proto

package protomd5

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Md5Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Md5Request) Reset() {
	*x = Md5Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_md5er_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Md5Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Md5Request) ProtoMessage() {}

func (x *Md5Request) ProtoReflect() protoreflect.Message {
	mi := &file_md5er_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Md5Request.ProtoReflect.Descriptor instead.
func (*Md5Request) Descriptor() ([]byte, []int) {
	return file_md5er_proto_rawDescGZIP(), []int{0}
}

func (x *Md5Request) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Md5Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *Md5Response) Reset() {
	*x = Md5Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_md5er_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Md5Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Md5Response) ProtoMessage() {}

func (x *Md5Response) ProtoReflect() protoreflect.Message {
	mi := &file_md5er_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Md5Response.ProtoReflect.Descriptor instead.
func (*Md5Response) Descriptor() ([]byte, []int) {
	return file_md5er_proto_rawDescGZIP(), []int{1}
}

func (x *Md5Response) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

var File_md5er_proto protoreflect.FileDescriptor

var file_md5er_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x64, 0x35, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x64, 0x35, 0x22, 0x20, 0x0a, 0x0a, 0x6d, 0x64, 0x35, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x21, 0x0a, 0x0b, 0x6d, 0x64, 0x35,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x32, 0x3d, 0x0a, 0x05,
	0x6d, 0x64, 0x35, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x12, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x64, 0x35, 0x2e, 0x6d, 0x64, 0x35, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x64, 0x35, 0x2e, 0x6d, 0x64,
	0x35, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x6d,
	0x64, 0x35, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x64,
	0x35, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_md5er_proto_rawDescOnce sync.Once
	file_md5er_proto_rawDescData = file_md5er_proto_rawDesc
)

func file_md5er_proto_rawDescGZIP() []byte {
	file_md5er_proto_rawDescOnce.Do(func() {
		file_md5er_proto_rawDescData = protoimpl.X.CompressGZIP(file_md5er_proto_rawDescData)
	})
	return file_md5er_proto_rawDescData
}

var file_md5er_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_md5er_proto_goTypes = []any{
	(*Md5Request)(nil),  // 0: protomd5.md5request
	(*Md5Response)(nil), // 1: protomd5.md5response
}
var file_md5er_proto_depIdxs = []int32{
	0, // 0: protomd5.md5er.md5:input_type -> protomd5.md5request
	1, // 1: protomd5.md5er.md5:output_type -> protomd5.md5response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_md5er_proto_init() }
func file_md5er_proto_init() {
	if File_md5er_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_md5er_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Md5Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_md5er_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Md5Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_md5er_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_md5er_proto_goTypes,
		DependencyIndexes: file_md5er_proto_depIdxs,
		MessageInfos:      file_md5er_proto_msgTypes,
	}.Build()
	File_md5er_proto = out.File
	file_md5er_proto_rawDesc = nil
	file_md5er_proto_goTypes = nil
	file_md5er_proto_depIdxs = nil
}
