// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: md5er.proto

package protomd5

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Md5Er_Md5_FullMethodName = "/protomd5.md5er/md5"
)

// Md5ErClient is the client API for Md5Er service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Md5ErClient interface {
	Md5(ctx context.Context, in *Md5Request, opts ...grpc.CallOption) (*Md5Response, error)
}

type md5ErClient struct {
	cc grpc.ClientConnInterface
}

func NewMd5ErClient(cc grpc.ClientConnInterface) Md5ErClient {
	return &md5ErClient{cc}
}

func (c *md5ErClient) Md5(ctx context.Context, in *Md5Request, opts ...grpc.CallOption) (*Md5Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Md5Response)
	err := c.cc.Invoke(ctx, Md5Er_Md5_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Md5ErServer is the server API for Md5Er service.
// All implementations must embed UnimplementedMd5ErServer
// for forward compatibility.
type Md5ErServer interface {
	Md5(context.Context, *Md5Request) (*Md5Response, error)
	mustEmbedUnimplementedMd5ErServer()
}

// UnimplementedMd5ErServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMd5ErServer struct{}

func (UnimplementedMd5ErServer) Md5(context.Context, *Md5Request) (*Md5Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Md5 not implemented")
}
func (UnimplementedMd5ErServer) mustEmbedUnimplementedMd5ErServer() {}
func (UnimplementedMd5ErServer) testEmbeddedByValue()               {}

// UnsafeMd5ErServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Md5ErServer will
// result in compilation errors.
type UnsafeMd5ErServer interface {
	mustEmbedUnimplementedMd5ErServer()
}

func RegisterMd5ErServer(s grpc.ServiceRegistrar, srv Md5ErServer) {
	// If the following call pancis, it indicates UnimplementedMd5ErServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Md5Er_ServiceDesc, srv)
}

func _Md5Er_Md5_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Md5Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Md5ErServer).Md5(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Md5Er_Md5_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Md5ErServer).Md5(ctx, req.(*Md5Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Md5Er_ServiceDesc is the grpc.ServiceDesc for Md5Er service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Md5Er_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protomd5.md5er",
	HandlerType: (*Md5ErServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "md5",
			Handler:    _Md5Er_Md5_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "md5er.proto",
}
